### ISSUE TITLE
CentOS 8 default firewall provider is firewalld not iptables

### ISSUE THREAD

**Issue by djessich** [sous-chefs/firewall#235]
## :ghost: Brief Description

CentOS 8 configures iptables instead of firewalld. Breaking any existing configuration from 2.7.1 version of this cookbook.

## :pancakes: Cookbook version

3.0.0

## :woman_cook:  Chef-Infra Version

16.13.16

## :tophat: Platform details

CentOS/RHEL 8

## Steps To Reproduce

Install firewall by this cookbook on CentOS 8 platform will install iptables instead of firewalld.

## :police_car: Expected behavior

Configure firewalld.

## :heavy_plus_sign: Additional context

In Version 2.7.1 of this cookbook, CentOS 8 will be configured with firewalld.

## Question

This change is not compatible with the CentOS 8, why was firewalld support for RHEL 8 dropped?

**Comment by Stromweld** [comment]
RedHat documentation 48.1.1 Actually recommends nftables which is a derivative of iptables and installs/configures the same as iptables.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-nftables_configuring-and-managing-networking

The firewall cookbook previously was updated in 2018 when RHEL7 was out and way before RHEL8 came out in 2019. In RHEL7 firewalld was the default installed firewall but in RHEL8 and above default install doesn't install any and expects you to choose one  at which they recommend nftables then unless you have a lot of scripts and automation built around firewalld. The cookbooks resources used a lot of version constraints and resources had version constraints simply set to >= rhel7, my guess due to expecting firewalld to be the default for future rhel versions.

firewalld wasn't dropped but default was updated to reflect current recommended firewall. The firewall resources in here need to be updated to modern chef resource patterns and should be split into seperate iptables, firewalld, nftables, ufw, windows firewall, etc... and let users choose which firewall to install and configure.
you can lock version to ~>2.x to maintain previous functionality and default.

**Comment by bmhughes** [comment]
> 
> 
> RedHat documentation 48.1.1 Actually recommends nftables which is a derivative of iptables and installs/configures the same as iptables.
> 
> https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/getting-started-with-nftables_configuring-and-managing-networking
> 
> The firewall cookbook previously was updated in 2018 when RHEL7 was out and way before RHEL8 came out in 2019. In RHEL7 firewalld was the default installed firewall but in RHEL8 and above default install doesn't install any and expects you to choose one at which they recommend nftables then unless you have a lot of scripts and automation built around firewalld. The cookbooks resources used a lot of version constraints and resources had version constraints simply set to >= rhel7, my guess due to expecting firewalld to be the default for future rhel versions.
> 
> firewalld wasn't dropped but default was updated to reflect current recommended firewall. The firewall resources in here need to be updated to modern chef resource patterns and should be split into seperate iptables, firewalld, nftables, ufw, windows firewall, etc... and let users choose which firewall to install and configure.
> you can lock version to ~>2.x to maintain previous functionality and default.

On the subject of firewalld it's my understanding that it's just a wrapper around iptables to provide a basic zone-based functionality rather than being a firewall itself and hooking into `netfilter` so it should apply to nftables as well as iptables at a higher level rather than being a replacement so it's not mutually exclusive there and you could still use it. (Personally it's the first thing I uninstall)

I looked at nftables a while ago (for the waiting PR on iptables) and it's probably a slight improvement over iptables from a cookbook perspective as you can accumulate a single configuration file but annoyingly it's still a custom format.
